receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "promscale:9202"
    tls:
      insecure: true
    sending_queue:
      queue_size: 1000000
    timeout: 10s
  prometheusremotewrite:
    endpoint: "http://promscale:9201/write"
    resource_to_telemetry_conversion:
      enabled: true # Convert resource attributes to metric labels
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging,prometheusremotewrite]
