version: "3"
services:

  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    ports:
      - 5432:5432/tcp
    volumes:
      - timescaledb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tsdb
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
        test: ls /var/run/postgresql/.s.PGSQL.5432 && sleep 5 || exit 1
        interval: 1s
        timeout: 10s
        retries: 20
    networks:
      - promscale

  promscale:
    image: timescale/promscale:latest
    ports:
      - 9201:9201/tcp
      - 9202:9202/tcp
    depends_on:
      timescaledb:
          condition: service_healthy
    environment:
      PROMSCALE_DB_URI: postgres://postgres:password@timescaledb:5432/tsdb?sslmode=allow
    networks:
      - promscale

  otel-collector:
    image: otel/opentelemetry-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
    depends_on:
      - promscale
    networks:
      - promscale

  grafana:
    image: grafana/grafana-oss
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000/tcp
    depends_on:
      - timescaledb
    networks:
      - promscale

  jaegger-query:
    image: jaegertracing/all-in-one:latest
    ports:
      - 16685:16685/tcp
      - 16686:16686/tcp
      - 16687:16687/tcp
      - 6831:6831/udp
      - 6832:6832/udp
      - 14268:14268
    environment:
      SPAN_STORAGE_TYPE: grpc-plugin
      GRPC_STORAGE_SERVER: promscale:9202
    depends_on:
      - promscale
    networks:
      - promscale  
 

volumes:
  timescaledb-data:
  grafana-data:

networks:
  promscale:
    driver: bridge